"""phase1 baseline schema

Revision ID: 0001
Revises:
Create Date: 2026-10-09 10:44:45.536024
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("cloud_llm_allowed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("password_hash", sa.String(length=300), nullable=False),
        sa.Column("role", sa.Enum("admin", "examiner", "teacher", name="role"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_users_org_id"), "users", ["org_id"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("entity_type", sa.String(length=60), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_actor_id"), "audit_logs", ["actor_id"], unique=False)
    op.create_table(
        "exams",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("course", sa.String(length=200), nullable=True),
        sa.Column("total_marks", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("policy", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_exams_org_id"), "exams", ["org_id"], unique=False)
    op.create_table(
        "exam_assignments",
        sa.Column("exam_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["exam_id"],
            ["exams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("exam_id", "user_id"),
    )
    op.create_index(op.f("ix_exam_assignments_user_id"), "exam_assignments", ["user_id"], unique=False)
    op.create_table(
        "submissions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("exam_id", sa.UUID(), nullable=False),
        sa.Column("student_ref", sa.String(length=200), nullable=False),
        sa.Column("consent_scope", sa.Enum("local_only", "public_release", name="consent_scope"), nullable=False),
        sa.Column("source_object_key", sa.String(length=500), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["exam_id"],
            ["exams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_submissions_exam_id"), "submissions", ["exam_id"], unique=False)
    op.create_table(
        "pages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("submission_id", sa.UUID(), nullable=False),
        sa.Column("page_no", sa.Integer(), nullable=False),
        sa.Column("object_key", sa.String(length=500), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("submission_id", "page_no"),
    )
    op.create_index(op.f("ix_pages_submission_id"), "pages", ["submission_id"], unique=False)
    op.create_table(
        "processing_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("submission_id", sa.UUID(), nullable=True),
        sa.Column(
            "status", sa.Enum("QUEUED", "RUNNING", "FAILED", "COMPLETED", "REVIEW_REQUIRED", name="job_status"), nullable=False
        ),
        sa.Column("current_stage", sa.String(length=40), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_processing_jobs_submission_id"), "processing_jobs", ["submission_id"], unique=False)
    op.create_table(
        "job_stage_attempts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("stage", sa.String(length=40), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("status", sa.Enum("STARTED", "SUCCEEDED", "FAILED", name="stage_status"), nullable=False),
        sa.Column("cache_key", sa.String(length=128), nullable=True),
        sa.Column("component_version", sa.String(length=40), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("output_ref", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["processing_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_stage_attempts_job_id"), "job_stage_attempts", ["job_id"], unique=False)
    op.create_table(
        "ocr_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("page_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("model_names", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("weights_sha256", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("component_version", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["page_id"],
            ["pages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ocr_runs_page_id"), "ocr_runs", ["page_id"], unique=False)
    op.create_table(
        "page_quality_flags",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("page_id", sa.UUID(), nullable=False),
        sa.Column("flag", sa.String(length=64), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("component_version", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["page_id"],
            ["pages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_page_quality_flags_flag"), "page_quality_flags", ["flag"], unique=False)
    op.create_index(op.f("ix_page_quality_flags_page_id"), "page_quality_flags", ["page_id"], unique=False)
    op.create_table(
        "ocr_lines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ocr_run_id", sa.UUID(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("polygon", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("bbox", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ocr_run_id"],
            ["ocr_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ocr_run_id", "line_no"),
    )
    op.create_index(op.f("ix_ocr_lines_ocr_run_id"), "ocr_lines", ["ocr_run_id"], unique=False)
    op.create_table(
        "line_corrections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("examiner_id", sa.UUID(), nullable=False),
        sa.Column("exam_id", sa.UUID(), nullable=False),
        sa.Column("submission_id", sa.UUID(), nullable=False),
        sa.Column("page_id", sa.UUID(), nullable=False),
        sa.Column("ocr_line_id", sa.UUID(), nullable=True),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("crop_object_key", sa.String(length=500), nullable=False),
        sa.Column("crop_sha256", sa.String(length=64), nullable=False),
        sa.Column("crop_bbox", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("crop_polygon", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("page_image_sha256", sa.String(length=64), nullable=False),
        sa.Column("preprocessing_version", sa.String(length=40), nullable=False),
        sa.Column("ocr_provider", sa.String(length=40), nullable=False),
        sa.Column("ocr_model_names", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ocr_weights_sha256", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ocr_text", sa.Text(), nullable=False),
        sa.Column("corrected_text", sa.Text(), nullable=False),
        sa.Column("edit_ops", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "consent_scope",
            postgresql.ENUM("local_only", "public_release", name="consent_scope", create_type=False),
            nullable=False,
        ),
        sa.Column("supersedes_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["exam_id"],
            ["exams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["examiner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ocr_line_id"],
            ["ocr_lines.id"],
        ),
        sa.ForeignKeyConstraint(
            ["page_id"],
            ["pages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["line_corrections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_line_corrections_exam_id"), "line_corrections", ["exam_id"], unique=False)
    op.create_index(op.f("ix_line_corrections_examiner_id"), "line_corrections", ["examiner_id"], unique=False)
    op.create_index(op.f("ix_line_corrections_submission_id"), "line_corrections", ["submission_id"], unique=False)
    # ### end Alembic commands ###

    # I8: append-only tables reject UPDATE and DELETE at the database level.
    op.execute("""
        CREATE FUNCTION grademind_forbid_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'append-only table %: % is not allowed (I8)', TG_TABLE_NAME, TG_OP USING ERRCODE = 'check_violation';
        END $$;
    """)
    for t in ("line_corrections", "audit_logs", "job_stage_attempts"):
        op.execute(
            f"CREATE TRIGGER {t}_append_only BEFORE UPDATE OR DELETE ON {t} FOR EACH ROW EXECUTE FUNCTION grademind_forbid_mutation()"
        )


def downgrade() -> None:
    for t in ("line_corrections", "audit_logs", "job_stage_attempts"):
        op.execute(f"DROP TRIGGER IF EXISTS {t}_append_only ON {t}")
    op.execute("DROP FUNCTION IF EXISTS grademind_forbid_mutation()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_line_corrections_submission_id"), table_name="line_corrections")
    op.drop_index(op.f("ix_line_corrections_examiner_id"), table_name="line_corrections")
    op.drop_index(op.f("ix_line_corrections_exam_id"), table_name="line_corrections")
    op.drop_table("line_corrections")
    op.drop_index(op.f("ix_ocr_lines_ocr_run_id"), table_name="ocr_lines")
    op.drop_table("ocr_lines")
    op.drop_index(op.f("ix_page_quality_flags_page_id"), table_name="page_quality_flags")
    op.drop_index(op.f("ix_page_quality_flags_flag"), table_name="page_quality_flags")
    op.drop_table("page_quality_flags")
    op.drop_index(op.f("ix_ocr_runs_page_id"), table_name="ocr_runs")
    op.drop_table("ocr_runs")
    op.drop_index(op.f("ix_job_stage_attempts_job_id"), table_name="job_stage_attempts")
    op.drop_table("job_stage_attempts")
    op.drop_index(op.f("ix_processing_jobs_submission_id"), table_name="processing_jobs")
    op.drop_table("processing_jobs")
    op.drop_index(op.f("ix_pages_submission_id"), table_name="pages")
    op.drop_table("pages")
    op.drop_index(op.f("ix_submissions_exam_id"), table_name="submissions")
    op.drop_table("submissions")
    op.drop_index(op.f("ix_exam_assignments_user_id"), table_name="exam_assignments")
    op.drop_table("exam_assignments")
    op.drop_index(op.f("ix_exams_org_id"), table_name="exams")
    op.drop_table("exams")
    op.drop_index(op.f("ix_audit_logs_actor_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_org_id"), table_name="users")
    op.drop_table("users")
    op.drop_table("organizations")
    # ### end Alembic commands ###
    for e in ("consent_scope", "role", "job_status", "stage_status"):
        op.execute(f"DROP TYPE IF EXISTS {e}")
