"""submission upload metadata (Phase 1 step 6: storage)

Sniffed MIME type, size and sanitised display filename of the stored source document, and one submission per
(exam, content hash) so a re-upload of the same file is detected. NOT NULL without a default: there is no deployed data
before Phase 1 ends.

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-09 11:02:23.039821
"""

import sqlalchemy as sa
from alembic import op

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("submissions", sa.Column("source_mime", sa.String(length=64), nullable=False))
    op.add_column("submissions", sa.Column("source_size_bytes", sa.BigInteger(), nullable=False))
    op.add_column("submissions", sa.Column("source_filename", sa.String(length=200), nullable=False))
    op.create_unique_constraint("uq_submissions_exam_source_sha256", "submissions", ["exam_id", "source_sha256"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_submissions_exam_source_sha256", "submissions", type_="unique")
    op.drop_column("submissions", "source_filename")
    op.drop_column("submissions", "source_size_bytes")
    op.drop_column("submissions", "source_mime")
    # ### end Alembic commands ###
