"""stage attempt seq and cache key index (Phase 1 step 1.5: jobs + SSE)

`seq` is a monotonic identity used as the SSE event id (created_at cannot order rows written in one transaction).
`cache_key` is indexed because every stage looks up a SUCCEEDED attempt by it before running.

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-09 11:09:21.337546
"""

import sqlalchemy as sa
from alembic import op

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("job_stage_attempts", sa.Column("seq", sa.BigInteger(), sa.Identity(always=True), nullable=False))
    op.create_index(op.f("ix_job_stage_attempts_cache_key"), "job_stage_attempts", ["cache_key"], unique=False)
    op.create_unique_constraint("uq_job_stage_attempts_seq", "job_stage_attempts", ["seq"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_job_stage_attempts_seq", "job_stage_attempts", type_="unique")
    op.drop_index(op.f("ix_job_stage_attempts_cache_key"), table_name="job_stage_attempts")
    op.drop_column("job_stage_attempts", "seq")
    # ### end Alembic commands ###
