"""job lease owner + heartbeat, idempotent stage outputs (D26)

`lease_owner` is the token of the worker holding a RUNNING job; `heartbeat_at` is renewed while a stage runs. A partial
unique index allows at most one SUCCEEDED attempt per cache key, so a duplicate run cannot record an output twice.

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-09 15:53:04.050842
"""

import sqlalchemy as sa
from alembic import op

revision = "0004"
down_revision = "0003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_job_stage_attempts_succeeded_cache_key",
        "job_stage_attempts",
        ["cache_key"],
        unique=True,
        postgresql_where=sa.text("status = 'SUCCEEDED'"),
    )
    op.add_column("processing_jobs", sa.Column("lease_owner", sa.UUID(), nullable=True))
    op.add_column("processing_jobs", sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("processing_jobs", "heartbeat_at")
    op.drop_column("processing_jobs", "lease_owner")
    op.drop_index(
        "uq_job_stage_attempts_succeeded_cache_key",
        table_name="job_stage_attempts",
        postgresql_where=sa.text("status = 'SUCCEEDED'"),
    )
    # ### end Alembic commands ###
