"""paper and rubric versions (Phase 2 step 2.3; D25 a/b)

Versioned question-paper structures and rubrics, one DRAFT per exam. Once a row is APPROVED a trigger forbids any
UPDATE or DELETE of it (I5/I8): changes create a new version.

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-09 16:31:13.556986
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

IMMUTABLE_WHEN_APPROVED = ("paper_versions", "rubric_versions")

revision = "0005"
down_revision = "0004"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "paper_sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("exam_id", sa.UUID(), nullable=False),
        sa.Column("object_key", sa.String(length=500), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("mime", sa.String(length=64), nullable=False),
        sa.Column("filename", sa.String(length=200), nullable=False),
        sa.Column("extracted_text", sa.Text(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["exam_id"],
            ["exams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_paper_sources_exam_id"), "paper_sources", ["exam_id"], unique=False)
    op.create_table(
        "paper_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("exam_id", sa.UUID(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("status", sa.Enum("DRAFT", "APPROVED", name="version_status"), nullable=False),
        sa.Column("document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["exam_id"],
            ["exams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["paper_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("exam_id", "version_no", name="uq_paper_versions_exam_version"),
    )
    op.create_index(op.f("ix_paper_versions_exam_id"), "paper_versions", ["exam_id"], unique=False)
    op.create_index(
        "uq_paper_versions_one_draft", "paper_versions", ["exam_id"], unique=True, postgresql_where=sa.text("status = 'DRAFT'")
    )
    op.create_table(
        "rubric_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("exam_id", sa.UUID(), nullable=False),
        sa.Column("paper_version_id", sa.UUID(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("status", postgresql.ENUM("DRAFT", "APPROVED", name="version_status", create_type=False), nullable=False),
        sa.Column("document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("policy", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["exam_id"],
            ["exams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["paper_version_id"],
            ["paper_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("exam_id", "version_no", name="uq_rubric_versions_exam_version"),
    )
    op.create_index(op.f("ix_rubric_versions_exam_id"), "rubric_versions", ["exam_id"], unique=False)
    op.create_index(
        "uq_rubric_versions_one_draft", "rubric_versions", ["exam_id"], unique=True, postgresql_where=sa.text("status = 'DRAFT'")
    )
    # ### end Alembic commands ###
    op.execute(
        """
        CREATE OR REPLACE FUNCTION grademind_forbid_approved_mutation() RETURNS trigger AS $$
        BEGIN
            IF OLD.status = 'APPROVED' THEN
                RAISE EXCEPTION '%: APPROVED versions are immutable (I5/I8); create a new version', TG_TABLE_NAME;
            END IF;
            IF TG_OP = 'DELETE' THEN
                RETURN OLD;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for t in IMMUTABLE_WHEN_APPROVED:
        op.execute(
            f"CREATE TRIGGER {t}_immutable_when_approved BEFORE UPDATE OR DELETE ON {t} "
            "FOR EACH ROW EXECUTE FUNCTION grademind_forbid_approved_mutation()"
        )


def downgrade() -> None:
    for t in IMMUTABLE_WHEN_APPROVED:
        op.execute(f"DROP TRIGGER IF EXISTS {t}_immutable_when_approved ON {t}")
    op.execute("DROP FUNCTION IF EXISTS grademind_forbid_approved_mutation()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_rubric_versions_one_draft", table_name="rubric_versions", postgresql_where=sa.text("status = 'DRAFT'"))
    op.drop_index(op.f("ix_rubric_versions_exam_id"), table_name="rubric_versions")
    op.drop_table("rubric_versions")
    op.drop_index("uq_paper_versions_one_draft", table_name="paper_versions", postgresql_where=sa.text("status = 'DRAFT'"))
    op.drop_index(op.f("ix_paper_versions_exam_id"), table_name="paper_versions")
    op.drop_table("paper_versions")
    op.drop_index(op.f("ix_paper_sources_exam_id"), table_name="paper_sources")
    op.drop_table("paper_sources")
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS version_status")
