"""page thumbnails and renderer (Phase 2 step 2.4: booklet -> page images)

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-09 16:35:59.833935
"""

import sqlalchemy as sa
from alembic import op

revision = "0006"
down_revision = "0005"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pages", sa.Column("thumb_object_key", sa.String(length=500), nullable=True))
    op.add_column("pages", sa.Column("renderer", sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pages", "renderer")
    op.drop_column("pages", "thumb_object_key")
    # ### end Alembic commands ###
