"""ocr runs: engine config hash, status, resolved config; append-only OCR tables (Phase 3 step 3.1; D28)

`config_hash` = sha256 of the RESOLVED engine configuration (rule 12). A partial unique index allows one OK run per
(page, config), so a duplicate or concurrent run cannot double-write. ocr_runs and ocr_lines become append-only (I8): the
0001 trigger function rejects UPDATE and DELETE. Existing rows (none in any deployment before this step) would get
status 'OK' and an empty config_hash.

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-10 12:32:07.175403
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

APPEND_ONLY = ("ocr_runs", "ocr_lines")

revision = "0008"
down_revision = "0007"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ocr_runs", sa.Column("status", sa.String(length=16), server_default="OK", nullable=False))
    op.add_column("ocr_runs", sa.Column("error", sa.Text(), nullable=True))
    op.add_column("ocr_runs", sa.Column("config_hash", sa.String(length=64), server_default="", nullable=False))
    op.add_column(
        "ocr_runs",
        sa.Column("resolved", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    )
    op.add_column("ocr_runs", sa.Column("image_width", sa.Integer(), nullable=True))
    op.add_column("ocr_runs", sa.Column("image_height", sa.Integer(), nullable=True))
    op.add_column("ocr_runs", sa.Column("latency_s", sa.Float(), nullable=True))
    op.create_index(
        "uq_ocr_runs_ok_page_config",
        "ocr_runs",
        ["page_id", "config_hash"],
        unique=True,
        postgresql_where=sa.text("status = 'OK'"),
    )
    # ### end Alembic commands ###
    for t in APPEND_ONLY:
        op.execute(
            f"CREATE TRIGGER {t}_append_only BEFORE UPDATE OR DELETE ON {t} FOR EACH ROW EXECUTE FUNCTION grademind_forbid_mutation()"
        )


def downgrade() -> None:
    for t in APPEND_ONLY:
        op.execute(f"DROP TRIGGER IF EXISTS {t}_append_only ON {t}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_ocr_runs_ok_page_config", table_name="ocr_runs", postgresql_where=sa.text("status = 'OK'"))
    op.drop_column("ocr_runs", "latency_s")
    op.drop_column("ocr_runs", "image_height")
    op.drop_column("ocr_runs", "image_width")
    op.drop_column("ocr_runs", "resolved")
    op.drop_column("ocr_runs", "config_hash")
    op.drop_column("ocr_runs", "error")
    op.drop_column("ocr_runs", "status")
    # ### end Alembic commands ###
