"""line corrections: a linear chain per line (Phase 3 step 3.4; D19, D28)

A correction can be superseded at most once and a line has at most one first correction, so two examiners editing the same line
at the same moment conflict (the loser gets a 409) instead of forking its history. Existing rows (none in any deployment before
this step) cannot violate either constraint.

Revision ID: 0009
Revises: 0008
Create Date: 2026-10-10 13:14:17.549146
"""

import sqlalchemy as sa
from alembic import op

revision = "0009"
down_revision = "0008"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_line_corrections_first_per_line",
        "line_corrections",
        ["ocr_line_id"],
        unique=True,
        postgresql_where=sa.text("supersedes_id IS NULL AND ocr_line_id IS NOT NULL"),
    )
    op.create_index(
        "uq_line_corrections_supersedes",
        "line_corrections",
        ["supersedes_id"],
        unique=True,
        postgresql_where=sa.text("supersedes_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_line_corrections_supersedes", table_name="line_corrections", postgresql_where=sa.text("supersedes_id IS NOT NULL")
    )
    op.drop_index(
        "uq_line_corrections_first_per_line",
        table_name="line_corrections",
        postgresql_where=sa.text("supersedes_id IS NULL AND ocr_line_id IS NOT NULL"),
    )
    # ### end Alembic commands ###
