"""Phase 0b GT-FREE proxies over all answer pages (not just the 7 transcribed ones). NOT accuracy metrics.

Rationale: these sheets contain almost no true digits (question labels and two percentages), so the number of digit
tokens an engine emits is dominated by invented digits (show-through, hallucination). Labels are counted separately
(digits at line start), so the proxy targets digits NOT at a line start. Also reports total lines and low-score lines.

Usage: python3 spike/proxy_0b.py --out-dir <dir> --cell LABEL=RUN_DIR:ENGINE_DIR [--cell ...] -> <dir>/phase0b_proxies.md
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from score import line_engine_lines  # noqa: E402

DIG = re.compile(r"\d+")
LABEL = re.compile(r"^\s*\d{1,2}(?=[\s.\]\):[]|$)")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out-dir", required=True)
    ap.add_argument("--cell", action="append", required=True)
    ap.add_argument("--low", type=float, default=0.6)
    args = ap.parse_args()
    run = Path(args.out_dir)
    run.mkdir(parents=True, exist_ok=True)
    rows = []
    for cell in args.cell:
        label, rest = cell.split("=", 1)
        run_dir, eng_dir = rest.rsplit(":", 1)
        for var in ["raw", "st010"]:
            for sheet in ["sheet_001", "sheet_002"]:
                d = Path(run_dir) / var / sheet / eng_dir
                recs = [json.loads(p.read_text()) for p in sorted(d.glob("page_*.json")) if p.stem != "page_01"]
                if not recs:
                    continue
                n_lines = sum(len(r["lines"]) for r in recs)
                low = sum(1 for r in recs for l in r["lines"] if l["score"] < args.low)
                non_label_digits = 0
                for r in recs:
                    for ln in line_engine_lines(r):
                        m = LABEL.match(ln)
                        non_label_digits += len(DIG.findall(ln[m.end():] if m else ln))
                rows.append((var, sheet, label, len(recs), n_lines, low, non_label_digits))
    out = ["| variant | sheet | engine | answer pages | lines | lines score<%.1f | non-label digit tokens |" % args.low,
           "|---|---|---|---|---|---|---|"]
    out += ["| " + " | ".join(str(x) for x in r) + " |" for r in rows]
    md = "\n".join(out) + ("\n\nGT-free proxies, NOT accuracy. Generated by `spike/proxy_0b.py`; do not edit by hand. "
                           "A c_* reader has the same line count as the B config whose boxes it reads.\n")
    (run / "phase0b_proxies.md").write_text(md)
    print(md)
    return 0


if __name__ == "__main__":
    sys.exit(main())
