"""Phase 0b GT-FREE proxies over all answer pages (not just the 7 transcribed ones). NOT accuracy metrics.

Rationale: these sheets contain almost no true digits (question labels and two percentages), so the number of digit
tokens an engine emits is dominated by invented digits (show-through, hallucination). Labels are counted separately
(digits at line start), so the proxy targets digits NOT at a line start. Also reports total lines and low-score lines.

Usage: python3 spike/proxy_0b.py --run spike/runs/<id>_phase0b   -> <run>/phase0b_proxies.md
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from score import line_engine_lines  # noqa: E402

DIG = re.compile(r"\d+")
LABEL = re.compile(r"^\s*\d{1,2}(?=[\s.\]\):[]|$)")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--run", required=True)
    ap.add_argument("--low", type=float, default=0.6)
    args = ap.parse_args()
    run = Path(args.run)
    rows = []
    for var in ["raw", "st010"]:
        for sheet in ["sheet_001", "sheet_002"]:
            for eng in ["b_mobile", "b_server", "c_trocr"]:
                d = run / var / sheet / eng
                recs = [json.loads(p.read_text()) for p in sorted(d.glob("page_*.json")) if p.stem != "page_01"]
                if not recs:
                    continue
                n_lines = sum(len(r["lines"]) for r in recs)
                low = sum(1 for r in recs for l in r["lines"] if l["score"] < args.low)
                non_label_digits = 0
                for r in recs:
                    for ln in line_engine_lines(r):
                        body = ln[LABEL.match(ln).end():] if LABEL.match(ln) else ln
                        non_label_digits += len(DIG.findall(body))
                rows.append((var, sheet, eng, len(recs), n_lines, low, non_label_digits))
    out = ["| variant | sheet | engine | answer pages | lines | lines score<%.1f | non-label digit tokens |" % args.low,
           "|---|---|---|---|---|---|---|"]
    out += ["| " + " | ".join(str(x) for x in r) + " |" for r in rows]
    md = "\n".join(out) + ("\n\nGT-free proxies, NOT accuracy. Generated by `spike/proxy_0b.py`; do not edit by hand. "
                           "Line counts for c_trocr equal b_server's (same detector boxes).\n")
    (run / "phase0b_proxies.md").write_text(md)
    print(md)
    return 0


if __name__ == "__main__":
    sys.exit(main())
