"""Phase 0c report tables (D22). Applies the PRE-REGISTERED decision rule in docs/PHASE_0C_PLAN.md mechanically.

Refuses unless both manifests are OWNER_VERIFIED (D21). With --selftest it runs on any GT status and writes ONLY to
--out (never PHASE_0C_REPORT.md), stamped NOT_REPORTABLE; used to test this code before real data exists.

Usage: python3 spike/report_0c.py --run spike/runs/<id> [--baseline spike/runs/20261008T091415Z_phase0b2] [--selftest --out f.md]
"""

from __future__ import annotations

import argparse
import difflib
import json
import re
import statistics
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "spike"))
from stats import bootstrap_ratio, compare, fmt_rate, fmt_ratio  # noqa: E402

SHEETS = ["sheet_001", "sheet_002"]
REPORT = ROOT / "PHASE_0C_REPORT.md"
THRESHOLD = 0.10  # pre-registered (docs/PHASE_0C_PLAN.md)


def status(s: str) -> str:
    return json.loads((ROOT / "data" / "transcriptions" / s / "manifest.json").read_text())["status"]


def table(hdr, rows):
    return "\n".join(["| " + " | ".join(hdr) + " |", "|" + "---|" * len(hdr)] +
                     ["| " + " | ".join("" if x is None else str(x) for x in r) + " |" for r in rows])


def run_py(script, *a):
    subprocess.run([sys.executable, str(ROOT / "spike" / script), *a], check=True, capture_output=True)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--run", required=True)
    ap.add_argument("--baseline", default=str(ROOT / "spike/runs/20261008T091415Z_phase0b2"))
    ap.add_argument("--selftest", action="store_true")
    ap.add_argument("--out")
    args = ap.parse_args()
    sts = {s: status(s) for s in SHEETS}
    owner = all(v == "OWNER_VERIFIED" for v in sts.values())
    if not owner and not args.selftest:
        print(f"refusing: GT status {sts}; Phase 0c tables require OWNER_VERIFIED (D21)", file=sys.stderr)
        return 2
    extra = [] if owner else ["--allow-draft"]  # selftest only
    ceil = Path(args.run) / "ceiling"
    resolved = json.loads((ceil / "resolved_models.json").read_text())
    work = Path(args.out).parent if args.out else ceil
    work.mkdir(parents=True, exist_ok=True)

    engines = {}
    for prov in ["anthropic", "gemini"]:
        for run_dir in sorted((ceil / prov).glob("run*")):
            engines[f"{prov}_{run_dir.name}"] = ("text", str(run_dir / "{sheet}"))
    engines["b_v6_baseline"] = ("lines", str(Path(args.baseline) / "raw" / "{sheet}" / "b_v6"))

    md = [f"_Generated by `spike/report_0c.py`; do not edit by hand._  ", f"GT status: {sts}  ",
          f"Label: **CEILING_REFERENCE**, benchmark only, never product path.  ",
          "Numeral / sign / unit accuracy: **UNTESTED** (D5).", ""]
    if not owner:
        md.insert(0, "# NOT_REPORTABLE: SELFTEST ON NON-OWNER-VERIFIED GT\n")
    circ = "" if owner else " **CIRCULAR** (GT not fully OWNER_VERIFIED; excluded from conclusions)"
    md += ["### C0. Resolved models (rule 12)", "",
           table(["provider", "resolved model", "prompt"], [[p, v.get("model"), f"{resolved['prompt']['id']}/{resolved['prompt']['version']} {resolved['prompt']['sha256'][:12]}"]
                                                          for p, v in resolved["models"].items()]), ""]

    # rule-12 / failure accounting
    rows = []
    for name in engines:
        if name == "b_v6_baseline":
            continue
        recs = [json.loads(f.read_text()) for f in Path(engines[name][1].replace("{sheet}", "")).rglob("page_*.json")]
        rows.append([name, len(recs), sum(r["rule12"] == "OK" for r in recs), sum(r["rule12"] == "RULE12_MISMATCH" for r in recs),
                     sum(r["rule12"] == "ERROR" for r in recs), sum(1 for r in recs if str(r.get("stop_reason")) in ("refusal", "max_tokens") or "MAX_TOKENS" in str(r.get("stop_reason"))),
                     round(statistics.median([r["latency_s"] for r in recs]), 1) if recs else None])
    md += ["### C1. Requests: OK / rule-12 mismatch / error / refusal-or-truncated", "",
           table(["engine/run", "pages", "OK", "RULE12_MISMATCH", "ERROR", "refusal/max_tokens", "median s/page"], rows), ""]

    # accuracy per engine/run per sheet
    rows = []
    for name, (fmt, tmpl) in engines.items():
        for s in SHEETS:
            out = work / f"c_score_{name}_{s}.json"
            run_py("score.py", "--gt", str(ROOT / "data/transcriptions" / s), "--engine", f"{name}={fmt}:{tmpl.format(sheet=s)}", "--out", str(out), *extra)
            sc = json.loads(out.read_text())
            t = sc["totals"].get(name)
            if not t:
                continue
            cp = [(e[name]["cer"] * e[name]["gt_chars"], e[name]["gt_chars"]) for e in sc["pages"].values() if name in e]
            lab = name + (circ if name.startswith("anthropic") else "")
            rows.append([lab, s, fmt_ratio(cp), t["omissions"], t["autocorrect_candidates"],
                         fmt_rate(t["labels_correct"], t["labels_detected"]), fmt_rate(t["labels_correct"], t["labels_gt"]),
                         t["option_letters_correct"], t["spurious_digit_tokens"]])
    md += ["### C2. Accuracy per engine/run and sheet (scorer page CER)", "",
           table(["engine/run", "sheet", "CER", "omissions", "autocorrect cand.", "label P", "label R", "options", "spurious digits"], rows), ""]

    # line-level CER (pre-registered definition): gate_metrics projection, per page, pooled over runs
    gargs = sum([["--gt", str(ROOT / "data/transcriptions" / s)] for s in SHEETS], [])
    for name, (fmt, tmpl) in engines.items():
        gargs += ["--engine", f"{name}={fmt}:{tmpl}"]
    gout = work / "c_gate.json"
    run_py("gate_metrics.py", *gargs, "--out", str(gout), *extra)
    g = json.loads(gout.read_text())
    pp = g["per_page_edits"]
    model_pages = {}
    for prov in ["anthropic", "gemini"]:
        runs = [n for n in engines if n.startswith(prov + "_run")]
        if runs:
            # one bootstrap unit per page = (sum of edits over runs, sum of chars over runs)
            model_pages[prov] = [(sum(x[r] for r in runs), x["chars"] * len(runs)) for x in pp.values()]
    model_pages["b_v6_baseline"] = [(x["b_v6_baseline"], x["chars"]) for x in pp.values()]
    ci = {k: bootstrap_ratio(v) for k, v in model_pages.items()}
    point = {k: sum(e for e, _ in v) / sum(c for _, c in v) for k, v in model_pages.items()}
    rows = [[k + (circ if k == "anthropic" else ""), fmt_ratio(v, unit="pages"), f"{ci[k][1]:.3f}" if ci[k] else None] for k, v in model_pages.items()]
    md += ["### C3. Line-level CER (pre-registered definition; pooled over both sheets and both runs)", "",
           table(["model", "line-level CER [95% CI] (n)", "upper 95% bound"], rows), ""]
    cloud = [k for k in ("anthropic", "gemini") if k in point and (owner or k != "anthropic")]
    md += ["Comparisons:", ""] + [f"- {a} vs {b}: **{compare(a, ci[a], b, ci[b])}**" for a, b in
                                   [("gemini", "anthropic"), ("gemini", "b_v6_baseline"), ("anthropic", "b_v6_baseline")] if a in ci and b in ci] + [""]

    # run-to-run variance (all 25 pages, no GT)
    rows = []
    for prov in ["anthropic", "gemini"]:
        r1, r2 = ceil / prov / "run1", ceil / prov / "run2"
        if not (r1.exists() and r2.exists()):
            continue
        neds, identical = [], 0
        for f1 in sorted(r1.rglob("page_*.json")):
            f2 = r2 / f1.relative_to(r1)
            if not f2.exists():
                continue
            a = "\n".join(json.loads(f1.read_text())["lines_text"])
            b = "\n".join(json.loads(f2.read_text())["lines_text"])
            neds.append(1 - difflib.SequenceMatcher(None, a, b, autojunk=False).ratio())
            identical += a == b
        if neds:
            rows.append([prov, len(neds), fmt_rate(identical, len(neds)), round(statistics.mean(neds), 4), round(max(neds), 4)])
    md += ["### C4. Run-to-run variance (run 1 vs run 2, all answer pages; no GT needed)", "",
           table(["provider", "pages", "byte-identical", "mean (1 - similarity)", "max"], rows), ""]

    # decision rule
    if not owner:
        verdict = "NOT APPLICABLE: GT is not OWNER_VERIFIED (selftest). The rule can only be applied to OWNER_VERIFIED GT."
    elif not cloud:
        verdict = "NOT APPLICABLE: no cloud model results."
    else:
        best = min(cloud, key=point.get)
        up = ci[best][1]
        passed = up <= THRESHOLD
        verdict = (f"Best cloud model: **{best}** (`{resolved['models'][best]['model']}`), line-level CER {point[best]:.3f}, upper 95% bound **{up:.3f}** "
                   f"{'≤' if passed else '>'} {THRESHOLD:.2f} → " +
                   ("**AI verdict suggestions become a P1 candidate** (consented cloud mode + local fine-tuning track)." if passed
                    else "**D19 stands as the long-term product shape.**"))
    md += ["### C5. Pre-registered decision rule (docs/PHASE_0C_PLAN.md)", "", verdict, ""]
    block = "\n".join(md)
    if args.selftest or not owner:
        Path(args.out or (work / "report_0c_SELFTEST.md")).write_text(block)
        print(block)
        return 0
    text = REPORT.read_text() if REPORT.exists() else "# PHASE 0C REPORT\n\n<!-- BEGIN GENERATED -->\n<!-- END GENERATED -->\n"
    REPORT.write_text(re.sub(r"<!-- BEGIN GENERATED -->.*<!-- END GENERATED -->",
                             "<!-- BEGIN GENERATED -->\n" + block.replace("\\", "\\\\") + "\n<!-- END GENERATED -->", text, flags=re.S))
    print(block)
    return 0


if __name__ == "__main__":
    sys.exit(main())
