"""Build the Phase 0b results table from runner and scorer outputs (spec §2 rule 1: numbers come only from
files the tools write). Writes <run>/phase0b_table.md and <run>/phase0b_table.json.

Per (engine, variant, sheet): s/page (answer pages, median), peak RSS / peak VRAM (max over page records),
and, ONLY if the sheet's transcriptions are OWNER_VERIFIED, the scorer's CER, WER, omissions, autocorrection
candidates, label P/R, option letters and spurious digits. Otherwise the accuracy cells say PENDING_VERIFICATION.

Usage: python3 spike/report_0b.py --run spike/runs/<id>_phase0b [--engine-a-ref spike/runs/<int8 run>]
"""

from __future__ import annotations

import argparse
import json
import statistics
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SHEETS = ["sheet_001", "sheet_002"]
ENGINES = {"b_mobile": "lines", "b_server": "lines", "c_trocr": "lines"}


def page_stats(d: Path) -> dict:
    recs = [json.loads(p.read_text()) for p in sorted(d.glob("page_*.json")) if p.stem != "page_01"]
    if not recs:
        return {}
    rss = [r.get("peak_rss_mib_process") for r in recs if r.get("peak_rss_mib_process") is not None]
    vram = [r.get("peak_torch_alloc_mib") for r in recs if r.get("peak_torch_alloc_mib") is not None]
    return {"answer_pages": len(recs), "s_per_page_median": round(statistics.median(r["latency_s"] for r in recs), 2),
            "peak_rss_mib": max(rss) if rss else None, "peak_vram_mib": max(vram) if vram else None}


def score(sheet: str, name: str, fmt: str, d: Path, out: Path) -> dict | None:
    gt = ROOT / "data" / "transcriptions" / sheet
    status = json.loads((gt / "manifest.json").read_text())["status"]
    if status != "OWNER_VERIFIED":
        return {"status": status}
    cmd = [sys.executable, str(ROOT / "spike" / "score.py"), "--gt", str(gt), "--engine", f"{name}={fmt}:{d}", "--out", str(out)]
    subprocess.run(cmd, check=True, capture_output=True)
    return json.loads(out.read_text())["totals"].get(name)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--run", required=True)
    ap.add_argument("--engine-a-ref", help="Phase 0 int8 run dir (sheet_*/engine_a), reference only: over D3 budget")
    args = ap.parse_args()
    run = Path(args.run)
    rows = []
    combos = [(e, v, s, run / v / s / e, f) for v in ["raw", "st010"] for s in SHEETS for e, f in ENGINES.items()]
    if args.engine_a_ref:
        combos += [("a_int8_ref", "raw", s, Path(args.engine_a_ref) / s / "engine_a", "a") for s in SHEETS]
    for eng, var, sheet, d, fmt in combos:
        if not d.is_dir():
            continue
        st = page_stats(d)
        sc = score(sheet, eng, fmt, d, run / f"scores_{var}_{sheet}_{eng}.json")
        rows.append({"engine": eng, "variant": var, "sheet": sheet, **st, "scores": sc})
    (run / "phase0b_table.json").write_text(json.dumps(rows, indent=1))

    hdr = ("| engine | variant | sheet | CER | WER | omissions | autocorrect cand. | label P / R | options | spurious digits "
           "| s/page | peak RAM MiB | peak VRAM MiB |")
    lines = [hdr, "|" + "---|" * 13]
    for r in rows:
        sc = r["scores"] or {}
        if "status" in sc:
            acc = ["PENDING_VERIFICATION"] + [""] * 6
        else:
            acc = [sc["cer_micro"], sc["wer_micro"], sc["omissions"], sc["autocorrect_candidates"],
                   f"{sc['label_precision']} / {sc['label_recall']}", sc["option_letters_correct"], sc["spurious_digit_tokens"]]
        lines.append("| " + " | ".join(str(x) for x in [r["engine"], r["variant"], r["sheet"], *acc,
                                                           r.get("s_per_page_median"), r.get("peak_rss_mib"),
                                                           r.get("peak_vram_mib")]) + " |")
    md = "\n".join(lines) + ("\n\nNumeral / sign / unit accuracy: **UNTESTED** (owner decision D5).\n"
                             "Generated by `spike/report_0b.py` from runner JSON and `spike/score.py` outputs; do not edit by hand.\n")
    (run / "phase0b_table.md").write_text(md)
    print(md)
    return 0


if __name__ == "__main__":
    sys.exit(main())
